{% set name = "genin2" %}
{% set version = "2.1.2" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2a8833966003750d5534451f00887687737810693721e253871403929106391a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --ignore-installed -vv"
  entry_points:
    # genin2 provides a console script, pip install handles this automatically.
    # If needed, you can list them here for conda to be aware:
    - genin2 = genin2.genin2:main

requirements:
  host: # Dependencies needed at build time
    - python >=3.13
    - pip
    - setuptools
    # - genin2==2.1.2


  run: # Dependencies needed at run time
    - python >=3.13
    - biopython ==1.85
    - certifi ==2025.4.26
    - charset-normalizer ==3.4.2
    - click ==8.2.1
    - docopt ==0.6.2
    - idna ==3.10
    - importlib_resources ==6.5.2
    - joblib ==1.5.1
    - numpy ==2.2.6
    - requests ==2.32.3
    - scikit-learn ==1.6.1
    - scipy ==1.15.3
    - threadpoolctl ==3.6.0
    - urllib3 ==2.4.0
    - yarg >=0.1.9 #0.1.10 - but is not yet in conda forge
    
test:
  imports: # Test by trying to import the package
    - genin2
  commands: # Test by running the command-line interface
    - genin2 --help

about:
  home: https://github.com/izsvenezie-virology/genin2
  license: GNU Affero General Public License v3.0
  license_file: LICENSE # The sdist from PyPI includes this file
  summary: 'GenInI: GENbank INput INIhibitor for an easy and standardized submission of FASTA and metadata to GISAID and GenBank'
  doc_url: https://github.com/izsvenezie-virology/genin2
  dev_url: https://github.com/izsvenezie-virology/genin2

extra:
  recipe-maintainers:
    - evezeyl