{% set name = "genin2" %}
{% set version = "2.1.2" %}
{% set sha256 = "428952edbad1686c4995b01cd0093d5f712f6d45edbf3e70b49c33b0a17c9c26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --ignore-installed -vv"
  entry_points:
    # genin2 provides a console script, pip install handles this automatically.
    # If needed, you can list them here for conda to be aware:
    - genin2 = genin2.cli:start_cli

requirements:
  host: # Dependencies needed at build time
    - python >=3.13
    - pip
    - setuptools


  run: # Dependencies needed at run time
    - python >=3.13
    - biopython ==1.85
    - certifi ==2025.4.26
    - charset-normalizer ==3.4.2
    - click ==8.2.1
    - docopt ==0.6.2
    - idna ==3.10
    - importlib_resources ==6.5.2
    - joblib ==1.5.1
    - numpy ==2.2.6
    - requests ==2.32.3
    - scikit-learn ==1.6.1
    - scipy ==1.15.3
    - threadpoolctl ==3.6.0
    - urllib3 ==2.4.0
    #0.1.10 - but is not yet in conda forge
    - yarg >=0.1.9
    
test:
  imports: # Test by trying to import the package
    - genin2
  commands: # Test by running the command-line interface
    - genin2 --help

about:
  home: https://github.com/izsvenezie-virology/genin2
  license: GNU Affero General Public License v3.0
  license_file: LICENSE # The sdist from PyPI includes this file
  summary: 'Genin2 is a lightining-fast bioinformatic tool to predict genotypes for clade 2.3.4.4b H5Nx viruses collected in Europe since October 2020.Genin2 identifies only epidemiologically relevant European genotypes, i.e., detected in at least 3 viruses collected from at least 2 countries.'
  doc_url: https://github.com/izsvenezie-virology/genin2
  dev_url: https://github.com/izsvenezie-virology/genin2